[package]
name = "mathlib"
version = "0.1.0"
edition = "2024"

[dependencies]
gmp-mpfr-sys = { version = "1", default-features = false, features = ["use-system-libs"] }
rug = { version = "1", default-features = false, features = ["integer", "rand", "rational"] }
